# Generated by Django 5.1.7 on 2026-05-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='body_photos/')),
                ('analysis', models.TextField(blank=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, help_text='Optional weight when photo was taken', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_analyses', to='project.member')),
            ],
            options={
                'verbose_name_plural': 'Body analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
